# database init, supports mysql too
database=h2
spring.sql.init.schema-locations=classpath*:db/${database}/schema.sql
spring.sql.init.data-locations=classpath*:db/${database}/data.sql

# Web
spring.thymeleaf.mode=HTML

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

# Internationalization
spring.messages.basename=messages/messages
#Security configuration
spring.security.oauth2.client.registration.keycloak.client-id=sb
spring.security.oauth2.client.registration.keycloak.provider=keycloak
spring.security.oauth2.client.registration.keycloak.client-secret=prYvhB2U8lUmXIcmX1GCXdbQm755DLdy
spring.security.oauth2.client.registration.keycloak.client-name=KEYCLOAK
spring.security.oauth2.client.registration.keycloak.scope=openid
spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:9081/realms/petclinic
# Actuator
management.endpoints.web.exposure.include=*

# Docker Compose
spring.docker.compose.lifecycle-management=start_only
spring.docker.compose.file=docker-compose.yml
spring.docker.compose.profiles.active=postgres

# Logging
logging.level.org.springframework=INFO
# logging.level.org.springframework.web=DEBUG
# logging.level.org.springframework.context.annotation=TRACE

# Maximum time static resources should be cached
spring.web.resources.cache.cachecontrol.max-age=12h
